services:
  razornotes:
    container_name: razor_brackets
    image: test_brackets
    ports:
      - "8080:8000"
    environment:
        ENVCONFIG: PROD
        APP_NAME: "Razor Brackets"
    volumes:
      - ./files_u:/app/app/static
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"  
    restart: unless-stopped

